spring.application.name=my-market-app

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

spring.r2dbc.url = r2dbc:h2:mem:///usersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

logging.level.com.iron.mymarket=DEBUG
logging.level.org.springframework.web.server.session=DEBUG
logging.level.org.springframework.web.server.adapter.HttpWebHandlerAdapter=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG


spring.data.redis.host = 127.0.0.1
spring.data.redis.port = 6379
spring.data.cache.time-to-live = PT1M

resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.paymentService.registerHealthIndicator=true

payment.service.url=http://payment-service:8081

# OAuth2 Client Configuration
spring.security.oauth2.client.registration.keycloak.client-id=market-app-client
spring.security.oauth2.client.registration.keycloak.client-secret=qYaCNSsUtT7rD58IumL7Q7aZPknfVhPN
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8080/login/oauth2/code/keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email


spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://keycloak:8080/realms/market-app-realm/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.token-uri=http://keycloak:8080/realms/market-app-realm/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8082/realms/market-app-realm/protocol/openid-connect/auth
#spring.security.oauth2.client.provider.keycloak.user-info-uri=http://keycloak:8080/realms/market-app-realm/protocol/openid-connect/userinfo
# OAuth2 Resource Server
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/market-app-realm