spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8082/realms/market-app-realm
spring.security.oauth2.client.registration.keycloak.client-id=market-app-client
spring.security.oauth2.client.registration.keycloak.client-secret=${KC_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.scope=openid,profile
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak