CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     external_id VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    username VARCHAR(255),
    CONSTRAINT uk_external_id UNIQUE (external_id)
    );

-- ITEMS
CREATE TABLE items
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description CLOB,
    img_path    VARCHAR(255),
    price       BIGINT       NOT NULL,
    count       INT          NOT NULL
);

-- ORDERS
CREATE TABLE orders
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total_sum BIGINT NOT NULL,
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ORDER_ITEMS
CREATE TABLE order_items
(
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id          BIGINT NOT NULL,
    item_id           BIGINT NOT NULL,
    quantity          INT    NOT NULL,
    price_at_purchase BIGINT NOT NULL,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
            REFERENCES orders (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_order_items_item
        FOREIGN KEY (item_id)
            REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS cart_items (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL,
      item_id BIGINT NOT NULL,
      quantity INT NOT NULL DEFAULT 1,
      CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );