server.port=8081
payment.initial.balance=1000000.00
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/market-app-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/market-app-realm/protocol/openid-connect/certs

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG


