# Database configuration
spring.datasource.url=r2dbc:h2:tcp://payment-db:9092/payment
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver

# Logging configuration
logging.level.com.iron.payment=INFO
logging.level.org.springframework.web=DEBUG
logging.level.reactor.netty=INFO

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server configuration
server.port=8081

# Initial balance
payment.initial.balance=1000000.00

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/market-app-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/market-app-realm/protocol/openid-connect/certs

